<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Champions Report</title>
    <style>
        /* Body and general styling */
        body {
            font-family: 'Arial', sans-serif;
            color: #333;
            margin: 30px;
            line-height: 1.6;
            background-color: #f4f7fa;
        }

        /* Header styling */
        h1 {
            text-align: center;
            color: #0056b3;
            font-size: 2rem;
            font-weight: bold;
            border-bottom: 3px solid #0056b3;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        h2 {
            color: #333;
            font-size: 1.75rem;
            margin-top: 0;
            font-weight: bold;
        }

        /* Information header */
        .header-info {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 1.1em;
            color: #555;
        }

        .header-info span {
            color: #0056b3;
            font-weight: bold;
        }

        /* Table styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f4f4f4;
            color: #333;
            font-weight: bold;
        }

        td {
            background-color: #ffffff;
        }

        tr:nth-child(even) td {
            background-color: #f9f9f9;
        }

        tr:hover td {
            background-color: #f1f1f1;
        }

        /* Colorful span elements */
        .text-success {
            color: #28a745;
            font-weight: bold;
        }

        .text-info {
            color: #17a2b8;
            font-weight: bold;
        }

        .text-purple {
            color: #6f42c1;
            font-weight: bold;
        }

        /* Responsive styling for better presentation in PDF */
        .container {
            max-width: 900px;
            margin: 0 auto;
        }

        /* Styling for additional details */
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.9rem;
            color: #777;
        }

        .footer a {
            color: #0056b3;
            text-decoration: none;
            font-weight: bold;
        }

    </style>
</head>

<body>
    <div class="container">

        <div class="header-info">
            <h2>Subject Champions</h2>
            <p>From <span class="text-success">{{ $className }}</span> for the <span class="text-success">{{ $examName }}</span> exam held in term <span class="text-info">{{ $term }}</span> of the year <span class="text-info">{{ $year }}</span>.</p>
            @if ($streamName)
                <p>For stream <span class="text-purple">{{ $streamName }}</span>.</p>
            @endif
        </div>

        <table>
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Student</th>
                    <th>Admission Number</th>
                    <th>Stream</th>
                    <th>Marks</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($champions as $champion)
                    @if ($champion && $champion->subject && $champion->student && $champion->student->section)
                        <tr>
                            <td>{{ $champion->subject->subject_name }}</td>
                            <td>{{ $champion->student->first_name }} {{ $champion->student->last_name }}</td>
                            <td>{{ $champion->student->adm_no }}</td>
                            <td>{{ $champion->student->section->name }}</td>
                            <td>{{ $champion->marks }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by <a href="#">Mbuku ERP</a></p>
        </div>
    </div>
</body>

</html>
